name: Build and Push Docs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Build the documentation
      run: |
        cd docs-source
        make githubclean  # Clean any old builds
        make github       # Build docs

    - name: Deploy docs to the repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        
        git remote set-url origin https://COMSOC-Community:${{ secrets.GITHUB_TOKEN }}@github.com/COMSOC-Community/pabutools.git
        
        # Assuming the built docs are in the /docs directory
        git add docs
        git commit -m "Automatic Deploy documentation"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this token for auth
